services:
  backend:
    container_name: server_staging
    env_file:
      - ./server/.env.staging
    environment:
      - NODE_ENV=staging
    ports:
      - "5001:5000"

  frontend:
    container_name: client_staging
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:5001/api
    ports:
      - "3001:80"
