apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: mern-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
