# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: NodePort
  selector:
    app: nginx-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000 # accessible from browser: http://<node-ip>:32000
